---
all:
  hosts:
    example_ubuntu:
      ansible_host: 18.193.101.39
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/ssh_frankfurt.pem
    example_centos:
      ansible_host: 35.157.139.13
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/ssh_frankfurt.pem
elasticsearch:
  hosts:
    example_centos:
    example_ubuntu:
          